### ISSUE TITLE
Dio Error 429 etc.

### ISSUE THREAD

**Issue by berkayhh** [hrvojecukman/chat_gpt_flutter#9]
I created a Loop for a Database and its sending for 1200 Row Post, 
after 20 or 30 POST im getting a Error like Too many Request or anyhting else. 
How can i check a Error in Commands as if else ? 
I wanna build it like ;
if ( Dio-Response = OK) {
gotonextnumber();
}else {
gotostartagain();}
Did u defined errors ? 
Im getting always 429- Too much Request , This Model used too much like this, 

429 - The engine is currently overloaded, please try again later | Cause: Our servers are experiencing high traffic.Solution: Please retry your requests after a brief wait.
-- | --

Thanks, 

Errors Code; 

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioError [DioErrorType.response]: Http status error [404]
#2      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:796:47)
#5      Future._completeError (dart:async/future_impl.dart:592:5)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:51:12)
#7      _Completer.completeError (dart:async/future_impl.dart:23:5)
#8      Future.any.onError (dart:async/future.dart:620:45)
#10     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:796:47)
#13     Future._completeError (dart:async/future_impl.dart:592:5)
#14     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:683:7)`

**Comment by berkayhh** [comment]
one more Output from Error ; 
`flutter:
flutter: ╔╣ DioError ║ Status: 429 Too Many Requests
flutter: ║  https://api.openai.com/v1/chat/completions
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter: ╔ DioErrorType.response
flutter: ║    {
flutter: ║         error: {
flutter: ║             "That model is currently overloaded with other requests. You can retry your re
flutter: ║             quest, or contact us through our help center at help.openai.com if the error p
flutter: ║             ersists. (Please include the request ID c37af7b0e7f58315e31aa3061267b6a5 in yo
flutter: ║             ur message.)"
flutter: ║             type: "server_error",
flutter: ║             param: null,
flutter: ║             code: null
flutter: ║        }
flutter: ║    }
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:`

**Comment by berkayhh** [comment]
`flutter:
flutter: ╔╣ Request ║ POST
flutter: ║  https://api.openai.com/v1/chat/completions
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter: ╔ Headers
flutter: ╟ content-type: application/json
flutter: ╟ Authorization: Bearer *********************************************/my Token Code/
flutter: ╟ contentType: application/json
flutter: ╟ responseType: ResponseType.json
flutter: ╟ followRedirects: true
flutter: ╟ connectTimeout: 0
flutter: ╟ receiveTimeout: 0
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter: ║ {"model":"gpt-3.5-turbo","messages":[{"role":"user","content":"****************************
flutter: ║ *************************************************************************************
flutter: ║ ********"}],"temperature":0.4,"top_p":null,"n":null,"stream":null,"stop":null,"max_toke
flutter: ║ ns":3000}
flutter:
flutter: ╔╣ DioError ║ Status: 429 Too Many Requests
flutter: ║  https://api.openai.com/v1/chat/completions
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter: ╔ DioErrorType.response
flutter: ║    {
flutter: ║         error: {
flutter: ║             "That model is currently overloaded with other requests. You can retry your re
flutter: ║             quest, or contact us through our help center at help.openai.com if the error p
flutter: ║             ersists. (Please include the request ID ******************** in yo
`

**Comment by zeqinjie** [comment]
me too~

**Comment by zeqinjie** [comment]
me too~ <img width="1217" alt="image" src="https://github.com/hrvojecukman/chat_gpt_flutter/assets/8444646/f061a662-dadf-4a08-8883-b65d13294993">

**Comment by loic-hamdi** [comment]
Same - the package is broken
